repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282 # Use the latest stable version of ruff
    hooks:
      - id: ruff
        args: [--fix] # Automatically fix formatting issues

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest stable version of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-black
    rev: v23.9.1 # Use the latest stable version of black
    hooks:
      - id: black
        language_version: python3 # Use Python 3

  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest stable version of black
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # Use the latest stable version of flake8
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0 # Use the latest stable version of pyupgrade
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"] # Upgrade syntax to Python 3.7+

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1 # Use the latest stable version of mypy
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"] # Add any additional type dependencies as needed

