services:
  api:
    container_name: api
    hostname: api
    shm_size: 1gb
    volumes:
      - ./api/App:/www/App
    build:
      context: api/.
    env_file:
      - ./api/.env
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - selenium

  selenium:
    container_name: selenium-service
    hostname: selenium
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 1gb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
