services:
  client:
    build:
      context: client/.
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api
    restart: always

  api:
    container_name: api
    volumes:
      - ./api/App:/app/App:rw
    build:
      context: api/.
    env_file:
      - ./api/.env
    environment:
      - SELENIUM_URL=http://selenium:4444
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - selenium

  selenium:
    container_name: selenium-service
    hostname: selenium
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 1gb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
